### ISSUE TITLE
Change configuration for projects

### ISSUE THREAD

**Issue by markuspoerschke** [andygrunwald/Jacobine#32]
The current configuration is aligned to the TYPO3 environment. Please provide a more flexible configuration. Please read the following concept of how the configuration can be changed:

The current config defines technologies. In this context that means "how". The "what" is static. But we have to define the "how" for our "what" for each project separately.

E.g.: Gitweb will crawl all available Repositories for this project. But there can be a different strategy for different project. So. We have a task and need a strategy how we can solve the task. We should provide some strategies for the tasks. Example:

```
Project_name:
    Gitweb: https://git.typo3.org/
```

should become something like that:

```
Project_name:
    Repositories:
        0:
            Strategy: GitWeb
            Options:
                Url: https://git.typo3.org/
        1:
            Strategy: GitHub
            Options:
                User: andygrunwald
        2:
            Strategy: static
            Options:
                List:
                    - git://code.domain.de/repo/
                    - svn://code.other-domain.com/trunk/
```

Note: I think we need a new architecture on to detect which task follows wich task. That has to be defined as well.
